apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: us.icr.io/sn-labs-imenabidi1/accounts:1
        name: accounts
        resources: {}
      env:
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_NAME
          valueFrom:
            secretRefKey:
              name: postgresql
              key: database-name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretRefKey:
              name: postgresql
              key: database-password 
        - name: DATABASE_USER
          valueFrom:
            secretRefKey:
              name: postgresql
              key: database-user 
status: {}
